### ISSUE TITLE
PhysioNet/CinC Challenge 2012

### ISSUE THREAD

**Issue by OluOrojo** [MIT-LCP/physionet#61]
I would like to find out if the test set used in the PhysioNet/CinC Challenge 2012 are available to the public.

I am a researcher looking to enhance mortality prediction in ICU I'd appreciate if I can have access to it as it would enhance my data set. Secondly, could you kindly suggest the best ways to integrate all the text data in the different sets

Thank you

**Comment by tompollard** [comment]
Hi again @OluOrojo. 

> I would like to find out if the test set used in the PhysioNet/CinC Challenge 2012 are available to the public.

I have raised this question in the past with the creators of the [2012 Challenge Dataset](https://physionet.org/challenge/2012/). Their preference was to keep the dataset private, so that the challenge could be re-run in the future if needed. Note that the dataset was extracted from MIMIC, so if you are working on mortality prediction then the MIMIC-III dataset may be a better focus for your work.

On your second question ("could you kindly suggest the best ways to integrate all the text data in the different sets"), please could you provide a little more detail? What text data are you referring to and what are you trying to achieve by aggregating it?

**Comment by tompollard** [comment]
This is a CSV file, which can be loaded into most data analysis packages, but it looks like line breaks are not being rendered in your screenshot for reasons that aren't clear to me. Take a look at an original dataset and you'll see that there are three columns:

```
Time,Parameter,Value
00:00,RecordID,132539
00:00,Age,54
00:00,Gender,0
00:00,Height,-1
00:00,ICUType,4
00:00,Weight,-1
```
